---
name: Repository Updater

# yamllint disable-line rule:truthy
on:
  workflow_call:
    secrets:
      UPDATER_TOKEN:
        required: true

permissions:
  contents: read

concurrency:
  group: queue

jobs:
  publish:
    name: Publish app update
    runs-on: ubuntu-latest
    steps:
      - name: ðŸš€ Run Repository Updater
        uses: hassio-addons/repository-updater@14898b0c7e7ae36eaf6e44f308765b8878d31177  # v2.0.0
        with:
          app: ${{ github.event.client_payload.app }}
          repository: ${{ github.repository }}
          token: ${{ secrets.UPDATER_TOKEN }}
